# 主要规则设置
select = ["E", "F", "W"]
ignore = []

# 目标 Python 版本
target-version = "py311"

# 行长度限制
line-length = 100

# 要排除的路径
exclude = [
    ".git",
    ".github",
    "__pycache__",
    "build",
    "dist",
    "*.egg-info",
]

# 额外配置
[lint]
# 允许未使用的变量名称（默认：_）
dummy-variable-rgx = "^(_|dummy|unused)$"