# 设置 Python 目标版本
target-version = "py311"

# 启用的规则集
select = ["E", "F", "W"]
ignore = []

# 行长度设置
line-length = 100

# 排除一些路径
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "build",
    "dist",
]